FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

COPY . .

RUN npx nx build api-service1

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist/api-service1 ./
EXPOSE 3000
CMD ["node", "main.js"]