FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
RUN npm install -g nx
COPY . .

RUN npx nx build api-service2

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist/api-service2 ./
EXPOSE 3001
CMD ["node", "main.js"]